//logical operators
// && and , || OR , ! NOT


/*
var age = 40;
if (age >= 18) {
    console.log("this is a true")
};
*/

//&& AND operators
/*
var age = 35;
if (age >= 18 && age <= 40) {
    console.log("this is a true")
};
*/


//&& AND operators
/*
var x = 10;
var y = 10;
if (x == 10 && y == 10) {
    console.log("true condation");
};
*/


//|| OR Operator
/*
var x = 10;
var y = 10;
if (x == 10 || y == 10) {
    console.log("true my condation");
};
*/

//|| OR Operator
/*
var x = 6;
var y = 10;
if (6 == 10 || y == 10) {
    console.log("true my condation..");
};
*/

// ! NOT Operators
/*
var x = 5;
var y = 10;
console.log(!x == y);
*/

//! NOT Operators
/*
var x = 10;
var y = 10;
console.log(!x == y);
*/

//! NOT Operators
/*
var x = 10;
var y = 10;
console.log(x == y);
*/

//Example with AND (&&):
/*
let age = 25;
//let hasID = true;
let hasID = false;

if (age >= 18 && hasID) {
    console.log("You can enter the club.");
} else {
    console.log("You cannot enter the club.");
}
    */

// Example with OR (||):
/*
let isWeekend = true;
let isHoliday = false;

if (isWeekend || isHoliday) {
    console.log("You can relax today.");
} else {
    console.log("It's a working day.");
}
    */

// Example with NOT (!):
/*
let isRaining = false;
//let isRaining = true;
if (!isRaining) {
    console.log("You can go for a walk.");
} else {
    console.log("Stay inside.");
}
    */



